### ISSUE TITLE
Spørsmål

### ISSUE THREAD

**Issue by Razmuzh** [Olen/home-assistant-skisporet#1]
Heisann, prøver å hente ut preppestatusen til et enkelt system jeg har på hytta. Bruker ikke Home-assistant, er kodet i micropython på en ESP-32.
Siden du har 'knekt koden' for hvordan man skal få ut disse dataene lurte jeg på om du har en 'oneliner' som vil gi bare 'timer siden prepp' for en gitt løypetrasé.

**Comment by Olen** [comment]
Hei,
En oneliner har jeg dessverre ikke.  Det du må gjøre er som beskrevet under "Config" i README, og finne en trackid.

Så kikker du i sensor.py, og der finner du to URLer:
https://github.com/Olen/home-assistant-skisporet/blob/0f0d3ff25c38e8423c81600a69ac8b8e9762ed2f/sensor.py#L116

og 
https://github.com/Olen/home-assistant-skisporet/blob/0f0d3ff25c38e8423c81600a69ac8b8e9762ed2f/sensor.py#L149

Jeg husker ikke nå nøyaktig hva og hvorfor, men jeg tror du må hente begge, og at den første gir deg en liste over alle de siste preppingene, og den andre gir mer data om en gitt prepping.  Så du må først sortere ut den nyeste av de du får i lista.

**Comment by Razmuzh** [comment]
Strålende, tusen takk!
