### ISSUE TITLE
Sensorer får verdi 'Unknown' etter oppdatering av skisporet.no

### ISSUE THREAD

**Issue by svhelge** [Olen/home-assistant-skisporet#6]
Hei!
Sensorene dukker opp som "Unknown" etter at skisporet.no nylig har gjort en oppdatering. 
Jeg tittet på det og fant ut at man kan få ut tid siden siste kjøring i JSON-format med følgende
`GET https://www.skisporet.no/map/segment/XXX?_data=routes/map/segment.$segmentId` 
der `XXX` er løypenr. 
Ved å bruke en jsonpath (`$.segment.newestPrep`) kan man hente ut verdiene (eksempel `{'level': 3, 'days': 2, 'hours': 16}`)

**Comment by Olen** [comment]
Takk,

Pusher en ny versjon snart.
Den kommer til å være en "BREAKING CHANGE" fordi en del ting har endra seg, men blir da også mulig å sette opp via GUI:

https://github.com/Olen/home-assistant-skisporet/tree/v2.0.0

**Comment by Olen** [comment]
Burde funke nå med nyeste versjon

**Comment by Olen** [comment]
Hei,
Kan du bekrefte at det funker fint for deg også etter 2.0-oppgradering?
Den ser i alle fall fin ut her.

**Comment by svhelge** [comment]
Hei!
Det fungerer bra, takk for oppdatering!
Litt uvant med UI-oppsett, det blir litt mye klikking for å legge til en ekstra løype. Men det gjøres dog kun en gang.
Savner "menyen" som man kan få opp via Integrations (tre prikker nede til høyre på "Integrations tile").

**Comment by Olen** [comment]
Godt å høre.
HA er ganske tydelige på at de ønsker GUI-oppsett, og som du sier.  Det gjøres bare én gang.  Tenkte også det var enklere å bare legge inn dele-linken direkte.
Hvilke prikker savner du?  Og hva forventet du å se på den menyen?

**Comment by svhelge** [comment]
Jeg tenker på disse "prikkene":
![image](https://user-images.githubusercontent.com/79386304/220121548-dccf88fc-68eb-4684-bf3d-4f7c2d2ddd57.png)
Kan man bruke "Configure" som en short-cut for å legge til en løype (slik at man slipper å gå via "Add Integration")?

**Comment by Olen** [comment]
Ah.  De tre prikkene dukker opp hvis du klikker på den enkelte løypa.

![image](https://user-images.githubusercontent.com/203184/220122805-7dd9f5fc-ce3b-401e-9346-a004b8d197fd.png)

Men, nei.  Du kan ikke bruke "configure" til å legge til en ny løype.  Den linken hadde i tilfelle vært for å endre oppsettet av en allerede konfigurert løype.  Per i dag er det ingenting å endre på, så menyen under prikkene gir deg bare standardvalgene for å fjerne eller disable integrasjonen, skru på debug-logging osv.

Hvis du vil spare deg et par klikk kan du bruke denne:

[![image](https://user-images.githubusercontent.com/203184/220123770-a5cbdf86-2d70-4a6e-9190-65b1a02a3879.png)](https://my.home-assistant.io/redirect/config_flow_start/?domain=skisporet)
